# Generated by Django 4.2.7 on 2023-11-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                ("updatedon", models.DateTimeField(auto_now=True)),
                ("isactive", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="VectorStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default="", max_length=12, unique=True)),
                ("title", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(max_length=200)),
                ("owner", models.CharField(max_length=50)),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                ("updatedon", models.DateTimeField(auto_now=True)),
                ("published", models.BooleanField(default=False)),
            ],
        ),
    ]
