# Generated by Django 4.2.7 on 2023-11-24 19:38

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                ("updatedon", models.DateTimeField(auto_now=True)),
                ("isactive", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="VectorStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=api.models.generate_unique_code_vectorstore,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(max_length=200)),
                ("owner", models.CharField(max_length=50)),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                ("updatedon", models.DateTimeField(auto_now=True)),
                ("published", models.BooleanField(default=False)),
                ("media_url", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="FileMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=200)),
                ("filesize", models.IntegerField()),
                ("filehash", models.CharField(max_length=200)),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                ("updatedon", models.DateTimeField(auto_now=True)),
                ("metadatafields", models.CharField(default="", max_length=200)),
                (
                    "vectorstore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.vectorstore",
                    ),
                ),
            ],
        ),
    ]
