# Generated by Django 4.2.7 on 2023-11-09 18:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vectorstore",
            name="media_url",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="vectorstore",
            name="code",
            field=models.CharField(
                default=api.models.generate_unique_code_vectorstore,
                max_length=12,
                unique=True,
            ),
        ),
    ]
