# Generated by Django 4.2.7 on 2023-11-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_vectorstore_media_url_alter_vectorstore_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vectorstore",
            name="media_url",
            field=models.CharField(default="", max_length=200, unique=True),
        ),
    ]
